app-web:
        build: ./web-docker
        ports:
                - "8080:8080"
        links:
                - app-db

app-db:
        build: ./db-docker
        expose:
                - "5432"
        volumes_from:
                - app-db-data
app-db-data:
        image: cogniteev/echo
        command: echo 'Data Container for PostgreSQL'
        volumes:
                - /var/lib/postgresql/data

